### ISSUE TITLE
mainStyles-responsive

### ISSUE THREAD

**Issue by Sayed94h** [Sayed94h/app-theme#21]
What I do I do in this step:

* Add CSS rules for the `webpage`
 ```CSS

body {
    font-family: 'open-sans', sans-serif;
    font-size: 17px;
    line-height: 1.5em;
    margin: 0;
    padding: 0;
    }

img {
    width: 100%;
}

.container {
    margin: auto;
}

/* COMMON CLASSES */

.primary-text {
    color: #56a79a;

}
.primary-background {
    background: #56a79a;
    
}

/* HEADER */

#main-header {

    border-bottom: 1px solid #56a79a;

}

/* NAVBAR */ 

#navbar {

    text-transform: uppercase;
}

#navbar li {

   display: inline;
   padding-right: 20px;
   list-style: none;

}

#navbar a {

  text-decoration: none;
  color: #888;
}

#navbar li.current a, #navbar a:hover {

    color: #56a79a;
    border-bottom: 3px solid #56a79a;
    padding-bottom: 3px;
}

/*  SHOWCASE */

#showcase {
    background: url('../images/showcase.jpg') no-repeat center center;
    border-bottom: 1px solid #56a79a;
    margin-bottom: 30px;
}

#showcase .row {
    height: 600px;
}

#showcase h2 {
    font-size: 50px;
    margin: 0;
    padding-bottom: 20px;
}

#showcase p {
    color: #ccc;
    margin: 0;
}

#showcase .showcase-content {
    background: #333;
    color: #fff;
    border-radius: 90px;
    padding: 40px;
    opacity: 0.9;
}

/* FEATURES */

#features h2 {
    font-size: 35px;
    margin: 0;
    padding-bottom: 10px;
}

#features p {
    color: #888;
    margin: 0;
    margin-bottom: 40px;
}

#features .fa {
    font-size: 60px;
    color: #56a79a;
}

/* INFO SECTION */

#info {
    background: #333 url('../images/info-bg.jpg') no-repeat;
    color: #fff;
}

#info h2 {
    font-size: 35px;
    margin: 0;
    padding-bottom: 10px;
}

#info ul {

    list-style: none;
    padding: 0;

}
#info ul {
 line-height: 2em;
 font-size: 20px;

}

/* COMPANY AREA */

#company {

    background: #333;
    color: #fff;
    padding: 10px 0;
}

#company h4 {
    text-transform: uppercase;
    margin-bottom: 0;
}

#company ul {

    padding: 0;
    list-style: none;
    line-height: 2em;    
}
#company input[type="text"] {
    padding: 7px;
}
#company button {
    background: #222;
    color: #fff;
    padding: 10px;
    border: 0;
}

/* FOOTER */

#main-footer {
    background: #56a79a;
    color: #fff;

}

/* PAGE */

#page {
    margin-bottom: 40px;
}

/* SERVICES */

.services ul li {
    list-style: none;
    padding: 10px;
}

.services ul li:nth-child(odd) {
    background: #56a79a;
    color: #fff;

}
.services ul li:nth-child(even) {
    background: #333;
    color: #fff;
}

/* CONTACT */

.contact form {
    background: #333;
    color: #fff;
    padding: 20px;
}

.contact form input[type="text"] {
    width: 50%;
    height: 30px;
    margin-bottom: 10px;
}

.contact form textarea {
    width: 50%;
    height: 100px;
}

.contact form button {
    width: 50%;
    padding: 10px 0;
    border: 0;
    background-color: #222;
    color: #fff;
}

.contact form label {
   text-transform: uppercase;
   
}

/* MEDIA QUERIES */ 

@media (max-width: 800px) {
    #showcase h1 {
        font-size: 30px;
    }
}

@media (max-width: 500px) {
    #showcase .showcase-content {
        padding: 40px 10px;
    }
}

```
